apiVersion: v1
kind: Service
metadata:
  name: node-server-service
spec:
  selector:
    app: node-server
  type: LoadBalancer
  ports:
    - name: node-server-service
      port: 80
      targetPort: 3000
      protocol: TCP
